// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUWNmdFYDic4auYqKMPmmwaeh6AFf8M38',
    appId: '1:746796827638:web:477d8bd765ae2986fcfdd7',
    messagingSenderId: '746796827638',
    projectId: 'shoply-app-ccb60',
    authDomain: 'shoply-app-ccb60.firebaseapp.com',
    databaseURL: 'https://shoply-app-ccb60-default-rtdb.firebaseio.com',
    storageBucket: 'shoply-app-ccb60.firebasestorage.app',
    measurementId: 'G-82QNYCMFRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbPy-VVK_EcumHp1YiqwXkheQmILntSGk',
    appId: '1:746796827638:android:9f775213b3ecc1f5fcfdd7',
    messagingSenderId: '746796827638',
    projectId: 'shoply-app-ccb60',
    databaseURL: 'https://shoply-app-ccb60-default-rtdb.firebaseio.com',
    storageBucket: 'shoply-app-ccb60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA33R-pRRTQ8pVdnYFB1w3eJIgWsacdpjo',
    appId: '1:746796827638:ios:884a9d9672591546fcfdd7',
    messagingSenderId: '746796827638',
    projectId: 'shoply-app-ccb60',
    databaseURL: 'https://shoply-app-ccb60-default-rtdb.firebaseio.com',
    storageBucket: 'shoply-app-ccb60.firebasestorage.app',
    iosClientId: '746796827638-1nqj93ir4n8o3bqd80jj5v442kta5a5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA33R-pRRTQ8pVdnYFB1w3eJIgWsacdpjo',
    appId: '1:746796827638:ios:884a9d9672591546fcfdd7',
    messagingSenderId: '746796827638',
    projectId: 'shoply-app-ccb60',
    databaseURL: 'https://shoply-app-ccb60-default-rtdb.firebaseio.com',
    storageBucket: 'shoply-app-ccb60.firebasestorage.app',
    iosClientId: '746796827638-1nqj93ir4n8o3bqd80jj5v442kta5a5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoply',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUWNmdFYDic4auYqKMPmmwaeh6AFf8M38',
    appId: '1:746796827638:web:994e28af25ede933fcfdd7',
    messagingSenderId: '746796827638',
    projectId: 'shoply-app-ccb60',
    authDomain: 'shoply-app-ccb60.firebaseapp.com',
    databaseURL: 'https://shoply-app-ccb60-default-rtdb.firebaseio.com',
    storageBucket: 'shoply-app-ccb60.firebasestorage.app',
    measurementId: 'G-5MK12XKRQ9',
  );
}
